version: '3'

services:
  web:
    build: .
    volumes:
      - ./src:/usr/src/app
    environment:
      - uwsgi_port=8080
    expose:
      - "8080"
    ports:
      - "8000:8080"
    command: "./start.sh"
